[package]
name = "phy-granular"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
description = "颗粒物质子系统:离散元(DEM)接触求解。"

[dependencies]
phy-core = { path = "../phy-core", version = "0.1.0" }
phy-math = { path = "../phy-math", version = "0.1.0" }
phy-rigid = { path = "../phy-rigid", version = "0.1.0" }
nalgebra.workspace = true
serde.workspace = true
num-traits = "0.2"
rayon.workspace = true
