[package]
name = "phy-demo"
edition.workspace = true
version.workspace = true

[dependencies]
phy-math = { path = "../phy-math" }
phy-rigid = { path = "../phy-rigid" }
phy-optics = { path = "../phy-optics" }
phy-fluid = { path = "../phy-fluid" }
phy-field = { path = "../phy-field" }
phy-soft = { path = "../phy-soft" }
phy-core = { path = "../phy-core" }
nalgebra = { workspace = true }
winit = "0.30"
softbuffer = "0.4"
