[package]
name = "phy-soft"
version = "0.1.0"
edition = "2021"

[dependencies]
phy-math = { path = "../phy-math" }
phy-core = { path = "../phy-core" }
phy-rigid = { path = "../phy-rigid" }
phy-fluid = { path = "../phy-fluid" }
phy-field = { path = "../phy-field" }
num-traits = "0.2"

[dev-dependencies]
